<h1>Feedback</h1>
<form method="post" role="form">
    <div class="form-group">
        <label class='control-label' id='label_log' data-title='допустимы латинские буквы, цифры, знаки - и _, не менее 3 символов' for="author">Author:</label>
        <input type="text" name="author" class="form-control" id="author" placeholder="Enter name" value="<?=$form->author?>" 
               onkeypress="keyPressAuthor(this)"  onblur='check_log()'/>
       <p class='error' id='author_error'></p>
    </div>
    <div class="form-group">
        <label class='control-label' for="email" >E-mail:</label>
        <input type="text" name="email" class="form-control" id="email" placeholder="Enter email" value="<?=$form->email?>"/>
        <p class='error' id='e_mail_error'></p>
    </div>
    <div class="form-group">
         <label class='control-label' for="message" >Message:</label>
        <textarea name="message" id="message" class="form-control" rows="3"><?=$form->message?></textarea>
        <p class='error' id='message_error'></p>
    </div>
    <p class='error' id='error'></p>
    <button type="submit" class="btn btn-default" >Go</button>
    
</form>