<h1>Feedback</h1>
<form method="post" role="form">
    <div class="form-group">
        <label for="author">Author</label>
        <input type="text" name="author" class="form-control" id="author" placeholder="Enter name" value="<?=$form->author?>"/>
    </div>
    <div class="form-group">
        <label for="author">Email</label>
        <input type="text" name="email" class="form-control" id="email" placeholder="Enter email" value="<?=$form->email?>"/>
    </div>
    <div class="form-group">
        <label for="message">Message</label>
        <textarea name="message" id="message" class="form-control" rows="3"><?=$form->message?></textarea>
    </div>
    <button type="submit" class="btn btn-default">Go</button>
</form>