<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <link rel="stylesheet" href="/css/style.css" type="text/css"/>

    <title>MVC</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
              <a class="navbar-brand" href="#">ADMIN</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/admin/index.php?route=book/index">Manage books</a></li>
            <li><a href="/admin/index.php?route=author/index">Manage authors</a></li>
            <li><a href="/admin/index.php?route=style/index">Manage styles</a></li>
            <!--<li><a href="/admin/index.php?route=feedback/index">Manage feedback</a></li>-->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
 
    <div class="container">

      <div class="starter-template" >
          <div class="after after-info <?= \Library\Session::getFlashStatus()?>" role="after">
            <?=\Library\Session::getFlash()?>
        </div> 
          
         <?=$content?>
      </div>

    </div><!-- /.container -->

    <footer>
        Copyright &copy; 2017
    </footer>
    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <script src="/js/jquery.js"></script>
    <script src="/js/script.js"></script>
    <script src="/js/feedback_js.js"></script>
    <script src="/js/bootstrap.min.js"></script>
  </body>
</html>